version: '3.8'


volumes:
  postgres_data:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - "80:80"
    depends_on:
      - web
