# Generated by Django 3.2 on 2021-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='ingredients_amounts', 
                through='recipes.RecipeIngredient', 
                to='recipes.Ingredient'),
        ),
    ]
