# Generated by Django 3.2 on 2021-05-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210521_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберите файл', upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
